/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryMotor.Frame;

import inventoryMotor.Controller.MainController;
import inventoryMotor.Helper.Helper;
import java.text.ParseException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hanas_bp
 */
public class MainFrame extends javax.swing.JFrame {
    private final MainController controller;
    private String motor_id;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        MainController mainController = new MainController();
        controller = mainController;
        
        loadTable();
        clearForm();
    }
    
    public String mesin(String mesin) {
        return mesin;
    }
    
    public String brand(String brand) {
        return brand;
    }
    
    public String nama(String nama) {
        return nama;
    }
    
    public String type(String type) {
        return type;
    }
    
    public String warna(String warna) {
        return warna;
    }
    
    public String jumlah(String jumlah) {
        return jumlah;
    }
    
    private void loadTable(){
        String sql = "select * from motor";
        controller.get(tb_motor, sql);
        System.out.println("Worked!");
    }
    
    private void clearForm(){
        cb_mesin.setSelectedIndex(0);
        cb_brand.setSelectedIndex(0);
        tf_nama.setText(null);
        cb_type.setSelectedIndex(0);
        dp_manufacture.setDate(null);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTime1 = new org.joda.time.DateTime();
        dateTime2 = new org.joda.time.DateTime();
        dateTime3 = new org.joda.time.DateTime();
        dateTime4 = new org.joda.time.DateTime();
        dateTime5 = new org.joda.time.DateTime();
        dateTime6 = new org.joda.time.DateTime();
        dateTime7 = new org.joda.time.DateTime();
        jPanel1 = new javax.swing.JPanel();
        cb_mesin = new javax.swing.JComboBox<>();
        cb_brand = new javax.swing.JComboBox<>();
        tf_nama = new javax.swing.JTextField();
        cb_type = new javax.swing.JComboBox<>();
        dp_manufacture = new org.jdesktop.swingx.JXDatePicker();
        tf_warna = new javax.swing.JTextField();
        tf_jumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_motor = new javax.swing.JTable();
        btn_submit = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        tf_search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        btn_search1 = new javax.swing.JButton();
        btn_ambilMotor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        cb_mesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "CM001", "CM002", "RC302", "GONE2", "CM034" }));
        cb_mesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mesinActionPerformed(evt);
            }
        });

        cb_brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Brand", "Yamaha ", "Honda ", "Suzuki" }));

        cb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Manual", "Matic" }));

        dp_manufacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_manufactureActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nomor Mesin");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Brand");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nama Motor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Manufacture");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Warna");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Jumlah");

        tb_motor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_motor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_motorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_motor);

        btn_submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Pencarian");

        btn_search.setText("Cari dengan Nama");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_search1.setText("Cari Brand");
        btn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search1ActionPerformed(evt);
            }
        });

        btn_ambilMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ambilMotor.setText("Ambil Motor");
        btn_ambilMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ambilMotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_jumlah)
                            .addComponent(dp_manufacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_warna)
                            .addComponent(cb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_nama)
                            .addComponent(cb_brand, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_mesin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_search1))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_submit)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_delete))
                            .addComponent(btn_ambilMotor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_mesin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search)
                            .addComponent(btn_search1))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dp_manufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_warna, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_submit)
                            .addComponent(btn_update)
                            .addComponent(btn_delete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ambilMotor)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dp_manufactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_manufactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dp_manufactureActionPerformed

    private void tb_motorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_motorMouseClicked

        try {
        // TODO add your handling code here:      
        Helper helper = new Helper();
        String id = helper.getValueRows(tb_motor, 0);
        String mesin = helper.getValueRows(tb_motor, 1);
        String brand = helper.getValueRows(tb_motor, 2);
        String nama = helper.getValueRows(tb_motor, 3);
        String type = helper.getValueRows(tb_motor, 4);
        String manufacture = helper.getValueRows(tb_motor, 5);
        String warna = helper.getValueRows(tb_motor, 6);
        String jumlah = helper.getValueRows(tb_motor, 7);
        
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        
        this.motor_id = id;
        cb_mesin.setSelectedItem(mesin);
        cb_brand.setSelectedItem(brand);
        tf_nama.setText(nama);
        cb_type.setSelectedItem(type);
        dp_manufacture.setDate(new Date(helper.getParsedDate(manufacture)));
        tf_warna.setText(warna);
        tf_jumlah.setText(jumlah);
        
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_tb_motorMouseClicked

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try {
        // TODO add your handling code here:
        String mesin = cb_mesin.getSelectedItem().toString();
        String brand = cb_brand.getSelectedItem().toString();
        String nama = tf_nama.getText();
        String type = cb_type.getSelectedItem().toString();
        
        Helper helper = new Helper();
        String manufacture = helper.parseDataToDatabase(dp_manufacture);
        String warna = tf_warna.getText();
        String jumlah = tf_jumlah.getText();
        
        String sql = "INSERT INTO motor (mesin, brand, name, types, "
                + "manufacture, color, jumlah) values (?,?,?,?,?,?,?)";
        
        Map<Integer, Object> map = new HashMap<>();
        map.put(1, mesin);
        map.put(2, brand);
        map.put(3, nama);
        map.put(4, type);
        map.put(5, manufacture);
        map.put(6, warna);
        map.put(7, jumlah);
        
        if (!controller.preparedStatement(map, sql)) {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan Data");
        }
        clearForm();
        loadTable();
        JOptionPane.showMessageDialog(null, "Berhasil Menambahkan Data");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        
        MainFrame lg = new MainFrame();
        String mesin = lg.mesin(cb_mesin.getSelectedItem().toString());
        String brand = lg.brand(cb_brand.getSelectedItem().toString());
        String nama = lg.brand(tf_nama.getText());
        String type = lg.type(cb_type.getSelectedItem().toString());
        String warna = lg.warna(tf_warna.getText());
        String jumlah = lg.warna(tf_jumlah.getText());
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
        // TODO add your handling code here:
        String mesin = cb_mesin.getSelectedItem().toString();
        String brand = cb_brand.getSelectedItem().toString();
        String nama = tf_nama.getText();
        String type = cb_type.getSelectedItem().toString();
        
        Helper helper = new Helper();
        String manufacture = helper.parseDataToDatabase(dp_manufacture);
        String warna = tf_warna.getText();
        String jumlah = tf_jumlah.getText();
        
        String sql = "UPDATE motor set mesin = ?, brand = ?, name = ?, types = ?, "
                + "manufacture = ?, color = ?, jumlah = ? WHERE id_motor = ?";
        
        Map<Integer, Object> map = new HashMap<>();
        map.put(1, mesin);
        map.put(2, brand);
        map.put(3, nama);
        map.put(4, type);
        map.put(5, manufacture);
        map.put(6, warna);
        map.put(7, jumlah);
        map.put(8, this.motor_id);
        
        if(controller.preparedStatement(map, sql)){
            clearForm();
            loadTable();
            JOptionPane.showMessageDialog(null, "Berhasil Merubah Data");
        } 
        else {
            JOptionPane.showMessageDialog(null, "Gagal Merubah Data");
        }
        
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            // TODO add your handling code here:
            Helper helper = new Helper();
            String manufacture = helper.parseDataToDatabase(dp_manufacture);

            String sql = "DELETE FROM motor WHERE id_motor = ?";

            Map<Integer, Object> map = new HashMap<>();
            map.put(1, this.motor_id);

            if(controller.preparedStatement(map, sql)){
                clearForm();
                loadTable();
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data");
            }    
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String search = tf_search.getText();
        String sql = "SELECT * FROM motor WHERE name LIKE '%" + search +"%';";
        controller.get(tb_motor, sql);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search1ActionPerformed
        // TODO add your handling code here:
        String search = tf_search.getText();
        String sql = "SELECT * FROM motor WHERE brand LIKE '%"+ search +"%';";
        controller.get(tb_motor, sql);
    }//GEN-LAST:event_btn_search1ActionPerformed

    private void cb_mesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mesinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_mesinActionPerformed

    private void btn_ambilMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ambilMotorActionPerformed
        // TODO add your handling code here:
        BuyMotor bm = new BuyMotor();
        bm.setVisible(true);
        this.setVisible(false);
             
    }//GEN-LAST:event_btn_ambilMotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ambilMotor;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search1;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_brand;
    private javax.swing.JComboBox<String> cb_mesin;
    private javax.swing.JComboBox<String> cb_type;
    private org.joda.time.DateTime dateTime1;
    private org.joda.time.DateTime dateTime2;
    private org.joda.time.DateTime dateTime3;
    private org.joda.time.DateTime dateTime4;
    private org.joda.time.DateTime dateTime5;
    private org.joda.time.DateTime dateTime6;
    private org.joda.time.DateTime dateTime7;
    private org.jdesktop.swingx.JXDatePicker dp_manufacture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_motor;
    private javax.swing.JTextField tf_jumlah;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_search;
    private javax.swing.JTextField tf_warna;
    // End of variables declaration//GEN-END:variables
}
